test: &default

  # Credentials for REST APIs
  client_id: AY4sZlRQEyKPbsfKjktC3tZpoXmgxngvj5Fyl35Mb-Cta20thXUK5GRelWlHpSR4dLk4BWw8fk7ZYHjN
  client_secret: ELG8hoOl9y3WLLkYoxpCWF7Q9vZlXk2Q80STiKHkM5bMVcfQeEKksAIsNrtLTRGAZPGeoIRZNSSlMIpG

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: ericmargules_api1.gmail.com
  password: 7K7KNNJX3XSQMTGZ
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AQxDViZYUw5YwcZFIVGAOoJaJhT5
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: eric.i.margules-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
